# Simple workflow for deploying static content to GitHub Pages
name: Deploy static link bio page

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy-to-vps"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    # get latest source code
      - name: Checkout Code
        uses: actions/checkout@v4
    # copy file from runner to web folder
      - name: deploy to web folder
        run: |
          echo "ðŸš€ Start deploy to server..."
          rsync -vr --delete --no-o --no-g --no-perms --omit-dir-times --exclude '.git' --exclude '.github' ./ /var/www/link-bio/rsync -vrlt --delete --no-o --no-g --exclude '.git' --exclude '.github' ./ /var/www/link-bio/
          echo "âœ… Welldone! Website is up to date."
        
        
        
